# Generated by Django 6.0.3 on 2026-04-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='seller',
        ),
    ]
