# Generated by Django 6.0.3 on 2026-04-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_owner_property_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
