# Generated by Django 6.0.3 on 2026-04-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='preview_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
