# Generated by Django 6.0.3 on 2026-04-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='preview_image',
            field=models.ImageField(blank=True, default='houseimage.png', upload_to=''),
        ),
    ]
