# Generated by Django 6.0.3 on 2026-04-10 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('transactions', '0004_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
            preserve_default=False,
        ),
    ]
